# Generated by Django 5.0.1 on 2024-02-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_question_end_date_question_start_date_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='title',
            new_name='text',
        ),
    ]
