# Generated by Django 5.0.1 on 2024-02-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_rename_title_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Question',
            new_name='question',
        ),
    ]
